#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

detect_lan_ip() {
  local ip=""

  if command -v ipconfig >/dev/null 2>&1; then
    ip="$(ipconfig getifaddr en0 2>/dev/null || true)"
    if [[ -z "$ip" ]]; then
      ip="$(ipconfig getifaddr en1 2>/dev/null || true)"
    fi
  fi

  if [[ -z "$ip" ]] && command -v ifconfig >/dev/null 2>&1; then
    ip="$(ifconfig 2>/dev/null | awk '/inet / && $2 !~ /^127\\./ {print $2; exit}')"
  fi

  if [[ -z "$ip" ]]; then
    ip="127.0.0.1"
  fi

  printf "%s" "$ip"
}

port_is_free() {
  local port="$1"
  ! lsof -iTCP:"$port" -sTCP:LISTEN >/dev/null 2>&1
}

pick_port() {
  local port="${1:-8000}"
  while ! port_is_free "$port"; do
    port=$((port + 1))
    if [[ "$port" -gt 8010 ]]; then
      echo "No free port found between 8000 and 8010." >&2
      exit 1
    fi
  done
  printf "%s" "$port"
}

LAN_IP="$(detect_lan_ip)"
PORT="$(pick_port 8000)"
DATA_DIR="$ROOT_DIR/data-test-server"
ENV_FILE="$ROOT_DIR/deploy/test-server.env"
ACCOUNT_REPORT="$DATA_DIR/lan_test_accounts.md"
PUBLIC_URL="http://$LAN_IP:$PORT"

mkdir -p "$ROOT_DIR/deploy" "$DATA_DIR/attachments" "$DATA_DIR/backups" "$DATA_DIR/imports" "$DATA_DIR/exports" "$ROOT_DIR/logs"

cat > "$ENV_FILE" <<EOF
# Auto-generated by scripts/one_click_lan_test_server.sh
JPT_DATA_DIR=$DATA_DIR
JPT_TEST_HOST=0.0.0.0
JPT_TEST_PORT=$PORT
JPT_PUBLIC_URL=$PUBLIC_URL
JPT_ROLLBACK_BACKUP=$ROOT_DIR/data/backups/rollback_v0.6_crud_baseline_20260504_023955.zip
EOF

echo
echo "JPT Sales Toolkit v0.9.0 LAN Test Server"
echo "--------------------------------------"
echo "Project:        $ROOT_DIR"
echo "Data directory: $DATA_DIR"
echo "Env file:       $ENV_FILE"
echo "Local URL:      http://127.0.0.1:$PORT"
echo "Team URL:       $PUBLIC_URL"
echo

echo "Step 1/4: checking Python dependencies"
python3 -m pip install -r requirements.txt >/dev/null

echo "Step 2/4: creating or refreshing test accounts"
python3 scripts/create_test_accounts.py \
  --data-dir "$DATA_DIR" \
  --include-existing-users \
  --report-path "$ACCOUNT_REPORT"

echo
echo "Current test dataset:"
python3 - <<PY
import sqlite3
from pathlib import Path
db = Path(r"$DATA_DIR") / "database.sqlite"
conn = sqlite3.connect(db)
counts = {
    "customers": conn.execute("SELECT COUNT(*) FROM customers").fetchone()[0],
    "leads": conn.execute("SELECT COUNT(*) FROM leads").fetchone()[0],
    "contacts": conn.execute("SELECT COUNT(*) FROM customer_contacts").fetchone()[0],
    "pre_sales_tasks": conn.execute("SELECT COUNT(*) FROM pre_sales_tasks").fetchone()[0],
    "after_sales_tasks": conn.execute("SELECT COUNT(*) FROM after_sales_tasks").fetchone()[0],
}
for key, value in counts.items():
    print(f"- {key}: {value}")
conn.close()
PY

echo
echo "Step 3/4: creating startup backup"
python3 scripts/backup_test_server.py --data-dir "$DATA_DIR"

echo
echo "Step 4/4: starting server"
echo
echo "Send this address to team members on the same LAN:"
echo "$PUBLIC_URL"
echo
echo "Account sheet:"
echo "$ACCOUNT_REPORT"
echo
echo "Included accounts:"
echo "- Demo accounts: leader01 / sales01 / sales02 / sales03 / tech01 / tech02"
echo "- Existing team users in this test database are also refreshed for LAN login"
echo
echo "Press Ctrl+C in this window to stop the server."
echo

python3 run.py --host 0.0.0.0 --port "$PORT" --data-dir "$DATA_DIR" --no-browser
