import { col } from './template_contract.mjs';

export const leadSheets = [
  {
    name: '商机', table: 'tbl_leads', title: '商机',
    description: '一条商机一行；owner_username 必须来自 App 成员目录。',
    columns: [
      col('action', '操作', { required: true, enum: 'actions' }),
      col('lead_key', '商机键', { required: true }),
      col('customer_key', '客户键', { required: true }),
      col('primary_contact_key', '主联系人键'),
      col('title', '商机标题', { required: true }),
      col('owner_username', '负责账号', { required: true }),
      col('sales_stage', '销售阶段', { required: true, enum: 'salesStages' }),
      col('inquiry_date', '询盘日期', { type: 'date' }),
      col('source_channel', '来源渠道', { enum: 'sourceChannels' }),
      col('quality_grade', '质量等级', { enum: 'qualityGrades' }),
      col('urgency', '紧急程度', { enum: 'urgencies' }),
      col('estimated_value', '预计金额', { type: 'number' }),
      col('product_category', '产品大类'), col('product_series', '产品系列'),
      col('quantity_text', '数量'), col('power_range', '功率范围'),
      col('wavelength', '波长'), col('application', '应用场景'),
      col('material', '材料'), col('special_requirements', '特殊要求'),
      col('potential_needs', '潜在需求'), col('quotation_id', '报价单号'),
      col('quotation_date', '报价日期', { type: 'date' }),
      col('po_number', 'PO号'), col('po_date', 'PO日期', { type: 'date' }),
      col('deal_amount', '成交金额', { type: 'number' }),
      col('currency', '币种', { enum: 'currencies' }),
      col('products_detail', '产品明细'),
      col('fulfillment_status', '履约状态', { enum: 'fulfillmentStatuses' }),
      col('lost_reason_code', '输单原因代码'), col('lost_reason_text', '输单说明'),
      col('supplemental_notes', '补充说明'),
    ],
  },
  {
    name: '商机协作成员', table: 'tbl_lead_assignments', title: '商机协作成员',
    description: 'owner 只填在商机表；这里仅填写 collaborator 或 watcher。',
    columns: [
      col('action', '操作', { required: true, enum: 'actions' }),
      col('assignment_key', '协作键', { required: true }),
      col('lead_key', '商机键', { required: true }),
      col('member_username', '成员账号', { required: true }),
      col('assignment_type', '协作类型', { required: true, enum: 'assignmentTypes' }),
    ],
  },
  {
    name: '互动记录', table: 'tbl_activities', title: '互动记录',
    description: '跟进和评论均一行一条；下一次跟进日期由 next_action_date 派生。',
    columns: [
      col('action', '操作', { required: true, enum: 'actions' }),
      col('activity_key', '互动键', { required: true }),
      col('lead_key', '商机键', { required: true }),
      col('activity_type', '互动类型', { required: true, enum: 'activityTypes' }),
      col('actor_username', '记录账号', { required: true }),
      col('occurred_at', '发生时间', { required: true, type: 'datetime' }),
      col('content', '内容', { required: true }),
      col('visibility', '可见范围', { required: true, enum: 'visibilities' }),
      col('method', '方式', { enum: 'activityMethods' }),
      col('status', '跟进状态', { enum: 'activityStatuses' }),
      col('response_date', '回复日期', { type: 'date' }),
      col('customer_feedback', '客户反馈'), col('next_action', '下一步行动'),
      col('next_action_date', '下一步日期', { type: 'date' }),
    ],
  },
];
